---

- name: Install gpg
  ansible.builtin.apt:
    name: gnupg,software-properties-common
    update_cache: yes
    cache_valid_time: 3600

- name: add gpg key
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: no

- name: add repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"             
    state: present
    validate_certs: no

- name: install grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600
