---

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
      tags:
        - alertmanager_install

- name: Install
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - alertmanager_configure

