---

- name: Install prometheus
  hosts: prom
  become: true
  roles:
    - role: roles/prometheus
      tags: prometheus

    - role: roles/alertmanager
      tags: alertmanager

    - role: roles/node_exporter
      tags: node_exporter   

    - role: roles/grafana
      tags: grafana   
                            
